### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by perone** [google-deepmind/xmanager#41]
Hi, just a quick question: what is the roadmap for xManager ? There are not many commits this year so it seems the project is not being maintained. Is there any official position on its continuation ? Thank you !

**Comment by alpiccioni** [comment]
Hey All,

Sorry for the delay in updating the Github repo and responding to issues. XManager is healthy and very well maintained internally, but we sometimes lose track of the open source version and things don't get pushed for a while :(

I've taken over support here and pushed the last year's (😅 ) worth of commits. I'll be going through to validate functionality so we're at a known-good base state, and then will be going through the issues and pull requests shortly afterwards. And hopefully create some processes so things get pushed pretty consistently :)

Thanks!
